# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

variables:
  deploy: false
  ACR_REPO: ''
  AZURE_SUBSCRIPTION: ''
  DOCKER_REPO: ''
  PACKAGE_NAME: ''

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm test
  displayName: 'npm test'

- task: Docker@2
  displayName: Login to ACR
  inputs:
    command: login
    containerRegistry: variables['ACR_REPO']

- task: Docker@2
  displayName: Build and Push
  inputs:
    command: buildAndPush
    repository: variables['DOCKER_REPO']
    tags: latest

- task: AzureRmWebAppDeployment@4
  condition: eq(variables['deploy'], 'true')
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: variables['AZURE_SUBSCRIPTION']
    appType: 'webAppContainer'
    WebAppName: variables['PACKAGE_NAME']
    DockerNamespace: variables['ACR_REPO']
    DockerRepository: variables['DOCKER_REPO']
    DockerImageTag: 'latest'
